### PR TITLE
Fixed grammar and made everything formal

### PR DESCRIPTION
**Pull request by pistonfish**
I fixed some mistakes and made everything clean and formal

### CODE REVIEW

**Comment by larsenv** [comment]
Thanks, now I need to copy it to the subdirectories.

**Comment by pistonfish** [comment]
Into 066, 078, 088 and 108?

**Comment by larsenv** [comment]
Yes, if you could copy it to those folders and make a PR that’d be great. I forgot about the PR myself.

**Comment by pistonfish** [comment]
I actually copied all the stuff today. Wait a sec.

**Pull request merged**
